name: NexusPowered
version: ${pluginVersion}
description: A Minecraft plugin utility to reduce boilerplate code in Bukkit plugins.
author: kubbidev
website: https://kubbidev.me
main: me.kubbidev.nexuspowered.internal.StandalonePlugin
load: STARTUP

# Soft depend on ProtocolLib for packets service impl
softdepend: [ ProtocolLib ]

# Mark the plugin as 1.13 compatible to avoid CB having to perform quite as much unnecessary
# remapping when the plugin is loaded.
api-version: 1.13