name: NexusPowered
version: ${project.version}
description: ${project.description}
author: kubbidev
website: ${project.url}
main: com.kubbidev.nexuspowered.paper.PaperNexusEngine
load: STARTUP
api-version: '1.20'

permissions:
  nexuspowered:
    default: op

  nexuspowered.info:
    default: op

  nexuspowered.help:
    default: op

  nexuspowered.reload:
    default: op

  nexuspowered.plugins:
    default: op